# This is what we'll set up via docker
destination:
  driver: RPostgres::Postgres
  args:
    host: orderly-db
    port: 5432
    user: postgres
    dbname: orderly
    password: schemaspy

# Compatible with montagu-reports, but later we'll need this to be
# tuneable I think.
fields:
  requester:
    required: true
    type: character
  author:
    required: true
    type: character
  comments:
    required: false
    type: character
